// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Menu.Infrastructure.EF.Contexts;

#nullable disable

namespace Restaurant.Menu.Infrastructure.Migrations
{
    [DbContext(typeof(PersistenceDbContext))]
    [Migration("20231028044706_InitialStructure")]
    partial class InitialStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Menu.Infrastructure.EF.PersistenceModel.CategoriaMenuPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("categoriaMenuItemId");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("categoriaMenu");
                });

            modelBuilder.Entity("Restaurant.Menu.Infrastructure.EF.PersistenceModel.MenuItemPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("menuItemId");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<Guid>("CategoriaMenuId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("categoriaMenuId");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaMenuId");

                    b.ToTable("menuItem");
                });

            modelBuilder.Entity("Restaurant.Menu.Infrastructure.EF.PersistenceModel.MenuItemPersistenceModel", b =>
                {
                    b.HasOne("Restaurant.Menu.Infrastructure.EF.PersistenceModel.CategoriaMenuPersistenceModel", "CategoriaMenu")
                        .WithMany()
                        .HasForeignKey("CategoriaMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaMenu");
                });
#pragma warning restore 612, 618
        }
    }
}
